// frontend/src/components/LeftColumnHeader.tsx
/**
 * LeftColumnHeader — Main Header Frame
 *
 * Lives inside the Main Content Area (right of LeftVerticalMenu), spanning
 * full width. This is the top-level frame for branding, navigation, and
 * prompt management controls.
 *
 * ─────────────────────────────
 * OUTER WRAPPER (flex-row)
 * ├── LeftVerticalMenu        ← far-left nav strip (collapsed by default)
 * └── Main Content (flex-col)
 *     ├── LeftColumnHeader    ← ** THIS COMPONENT **
 *     │   ├── ROW 1: Brand / Navigation (golden bg)
 *     │   │   LEFT:  LOGO_PLACEHOLDER
 *     │   │   RIGHT: NAV_TABS_PLACEHOLDER
 *     │   │
 *     │   └── ROW 2: Prompt Management Bar (white bg)
 *     │       LEFT:  PROMPT_TITLE_PLACEHOLDER
 *     │       RIGHT: PROMPT_CONTROLS → VERSION, TAGS, ID, AUTHOR,
 *     │               SCORE, COLUMN_FLIP
 *     │
 *     └── ResizableSplitter   ← 3 prompt columns
 *         ├── Left Column  (editor / chat when flipped)
 *         ├── Right Column (chat / editor when flipped)
 *         └── Third Column (injectable middle slot)
 * ─────────────────────────────
 *
 * COLUMN_FLIP is the final control in Row 2 — a deliberate config action
 * (not a drag) that swaps left/right column positions via layout state.
 */

import { useState, useRef, useEffect, useCallback } from "react";
import useEmblaCarousel from "embla-carousel-react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { ColumnFlipToggle } from "@/components/ColumnFlipToggle";
import VersionManager from "./VersionManager";
import { getStoredUserId } from "@/services/authService";

interface LeftColumnHeaderProps {
  // === ROW 1 PROPS ===
  logo?: React.ReactNode;
  navTabs?: React.ReactNode;

  // === ROW 2 PROPS ===
  promptTitle?: string;
  version?: string;
  /** Live current_version of the session, so the version list can refresh. */
  currentVersion?: number;
  tags?: string;
  promptId?: string;
  author?: string;
  score?: string;

  // === LAYOUT CONTROLS ===
  flipped?: boolean;
  onToggleFlip?: () => void;

  // === TITLE EDITING ===
  onTitleChange?: (newTitle: string) => void;
  activeTab?: string | null;
  onTabChange?: (tabId: string | null) => void;
}

export default function LeftColumnHeader({
  logo,
  navTabs,
  promptTitle,
  version,
  currentVersion,
  tags,
  promptId,
  author,
  score,
  flipped,
  onToggleFlip,
  onTitleChange,
  activeTab: externalActiveTab,
  onTabChange,
}: LeftColumnHeaderProps) {
  const [internalActiveTab, setInternalActiveTab] = useState<string | null>("composer");
  const activeTab = externalActiveTab ?? internalActiveTab;
  const setActiveTab = onTabChange ?? setInternalActiveTab;
  const [isEditingTitle, setIsEditingTitle] = useState(false);
  const [editedTitle, setEditedTitle] = useState(promptTitle || "");
  const titleInputRef = useRef<HTMLInputElement>(null);
  const justSavedRef = useRef(false); // Prevents sync from overwriting during save

  // Sync when prop changes externally (but not right after we save)
  useEffect(() => {
    if (!isEditingTitle && !justSavedRef.current) {
      setEditedTitle(promptTitle || "");
    }
    justSavedRef.current = false;
  }, [promptTitle, isEditingTitle]);

  // Focus input when editing starts
  useEffect(() => {
    if (isEditingTitle && titleInputRef.current) {
      titleInputRef.current.focus();
      titleInputRef.current.select();
    }
  }, [isEditingTitle]);

  const handleTitleSave = useCallback(() => {
    setIsEditingTitle(false);
    const trimmed = editedTitle.trim();
    if (trimmed && trimmed !== promptTitle && onTitleChange) {
      justSavedRef.current = true; // Block the next sync — our saved value is already in editedTitle
      onTitleChange(trimmed);
    }
  }, [editedTitle, promptTitle, onTitleChange]);

  const handleTitleKeyDown = useCallback((e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      handleTitleSave();
    } else if (e.key === "Escape") {
      setIsEditingTitle(false);
      setEditedTitle(promptTitle || "");
    }
  }, [handleTitleSave, promptTitle]);

  /*
   * EVALUATION IS DISABLED, on the owner's instruction (2026-09-18). Drawn and inert: the tab
   * is in the design and he asked for it disabled, not for it gone — so it keeps its place in
   * the row, takes no click, and says what it is (aria-disabled, a title, a muted label) rather
   * than looking like a tab that is broken. Everything else in the row still works.
   */
  const navTabDefs = [
    { id: 'console', label: 'Console' },
    { id: 'composer', label: 'Composer' },
    { id: 'evaluation', label: 'Evaluation', disabled: true },
    { id: 'variables', label: 'Variables' },
    { id: 'metadata', label: 'Metadata' },
  ];

  // ── Embla carousel for nav tabs — no dragFree so tabs stay
  //     in place during splitter resize operations ──
  const [navCarouselRef, navApi] = useEmblaCarousel({
    align: "start",
    dragFree: false,
    containScroll: "trimSnaps",
  });
  const [navCanScrollPrev, setNavCanScrollPrev] = useState(false);
  const [navCanScrollNext, setNavCanScrollNext] = useState(false);

  useEffect(() => {
    if (!navApi) return;
    const onSelect = () => {
      setNavCanScrollPrev(navApi.canScrollPrev());
      setNavCanScrollNext(navApi.canScrollNext());
    };
    navApi.on("select", onSelect);
    navApi.on("reInit", onSelect);
    onSelect();
    return () => {
      navApi.off("select", onSelect);
      navApi.off("reInit", onSelect);
    };
  }, [navApi]);

  return (
    <div
      id="left-column-header"
      data-ui-id="main-header-frame"
      data-ui-type="layout"
      data-ui-description="Main header frame — branding, nav, and prompt management controls"
      className="flex flex-col"
      style={{ 
        flexShrink: 0,
        minHeight: '56px',
        maxHeight: '100vh',
        position: 'relative',
        zIndex: 1,
        boxShadow: '0 8px 24px rgba(0, 0, 0, 0.25)'
      }}
    >
      {/* ════════════════════════════════════════════════════════════
          ROW 1: Brand / Navigation bar (golden/amber background)
          ════════════════════════════════════════════════════════════ */}
      <div
        data-ui-id="brand-nav-bar"
        data-ui-type="navigation"
        data-ui-description="Brand logo and navigation tabs"
        className="flex items-center justify-between px-4"
        style={{
          backgroundColor: "#19213c",
          minHeight: "56px",
        }}
      >
        {/* LOGO — fixed width, centered below 768px, left-aligned above */}
        <div
          data-lit-id="brand-logo"
          data-lit-type="content-area"
          data-lit-description="Brand logo — fixed width, centers at mobile, left-aligned at desktop"
          className="flex items-center gap-3 select-none md:justify-start justify-center md:pl-0 pl-[48px]"
          style={{ flex: "1 1 0%", minWidth: 0 }}
        >
          {logo ?? null}
        </div>

        {/* NAV_TABS — hidden below 768px (rolls into hamburger) */}
        <div
          data-lit-id="nav-tabs-carousel"
          data-lit-type="carousel"
          data-lit-description="Horizontal carousel nav — hidden below 768px, rolls into mobile hamburger"
          className="items-center gap-1 min-w-0 md:flex hidden"
        >
          {navTabs ?? (
            <div className="flex items-center gap-1 min-w-0">
              {/* Left arrow */}
              <button
                data-lit-id="nav-carousel-prev"
                data-lit-type="carousel-arrow"
                onClick={() => navApi?.scrollPrev()}
                disabled={!navCanScrollPrev}
                className="shrink-0 p-1 rounded-full transition-opacity"
                style={{ opacity: navCanScrollPrev ? 0.7 : 0.2 }}
                aria-label="Scroll tabs left"
              >
                <ChevronLeft className="w-4 h-4" style={{ color: "#1a1a1a" }} />
              </button>

              {/* Carousel viewport */}
              <div ref={navCarouselRef} className="overflow-hidden min-w-0">
                <div className="flex gap-1">
                  {navTabDefs.map((tab) => {
                    const isActive = activeTab === tab.id;
                    const isDisabled = (tab as { disabled?: boolean }).disabled === true;
                    return (
                      <button
                        key={tab.id}
                        data-lit-id={`nav-tab-${tab.id}`}
                        data-lit-type="tab"
                        data-lit-parent="nav-tabs-carousel"
                        /*
                         * A TAB IS NOT A TOGGLE. This read `isActive ? null : tab.id`, so
                         * clicking the tab you were ALREADY on set the header tab to null —
                         * and a null tab renders the workspace slot, which is the composer's.
                         * Clicking Console therefore landed you on Composer (owner,
                         * 2026-09-18: "when I click console, if it's already selected,
                         * instead of reloading the page it moves to composer").
                         *
                         * The rule he gave is simpler than what was here: "clicking a tab
                         * that's already selected reloads that surface." So the click always
                         * reports the tab it names; the host decides what a repeat means —
                         * for the console, re-assemble it; for the composer, a fresh package,
                         * which is what it has always meant.
                         */
                        disabled={isDisabled}
                        aria-disabled={isDisabled || undefined}
                        title={isDisabled ? 'Not wired up yet' : undefined}
                        onClick={() => { if (!isDisabled) setActiveTab(tab.id); }}
                        className={`flex items-center gap-1 px-3 py-1.5 rounded text-sm font-medium transition-colors whitespace-nowrap shrink-0 ${isDisabled ? 'cursor-default' : 'cursor-pointer'}`}
                        style={{
                          color: "#b6afbd",
                          backgroundColor: isActive && !isDisabled ? "rgba(0,0,0,0.10)" : "transparent",
                          border: isActive && !isDisabled ? "1px solid #3e243c" : "1px solid transparent",
                        }}
                      >
                        <svg viewBox="0 0 16 16" fill="none" className="w-3.5 h-3.5 opacity-70">
                          <rect x="2" y="2" width="12" height="12" rx="2" stroke="currentColor" strokeWidth="1.5" />
                          <path d="M5 8h6M8 5v6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                        </svg>
                        {tab.label}
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Right arrow */}
              <button
                data-lit-id="nav-carousel-next"
                data-lit-type="carousel-arrow"
                onClick={() => navApi?.scrollNext()}
                disabled={!navCanScrollNext}
                className="shrink-0 p-1 rounded-full transition-opacity"
                style={{ opacity: navCanScrollNext ? 0.7 : 0.2 }}
                aria-label="Scroll tabs right"
              >
                <ChevronRight className="w-4 h-4" style={{ color: "#1a1a1a" }} />
              </button>
            </div>
          )}
        </div>

        {/* IDENTITY CHIP — always visible, every tab.
            A2UI honesty: the console assembles packages owned by THIS identity.
            If the console looks empty, check this id against the package owner. */}
        <div style={{ flex: "1 1 0%", display: "flex", justifyContent: "flex-end", minWidth: 0 }}>
          <div
            data-lit-id="identity-chip"
            data-lit-type="content-area"
            data-lit-description="Active user identity — console assembles packages owned by this user"
            className="shrink-0 font-mono text-xs px-2 py-1 rounded select-all md:block hidden"
            style={{ color: "rgba(0,0,0,0.75)", backgroundColor: "rgba(255,255,255,0.35)" }}
            title={`Active identity: ${getStoredUserId()}\nThe console assembles prompt packages owned by this user.`}
          >
            u:{getStoredUserId().slice(0, 8)}…{getStoredUserId().slice(-4)}
          </div>
        </div>
      </div>

      {/* ════════════════════════════════════════════════════════════
          ROW 2: Prompt Management Bar (white background)
          Only visible when NOT on Console tab
          ════════════════════════════════════════════════════════════ */}
      {activeTab !== "console" && (
      <div
        data-ui-id="prompt-management-bar"
        data-ui-type="layout"
        data-ui-description="Prompt controls: title, version, tags, ID, author, score, column flip"
        className="flex items-center justify-between px-4 gap-4"
        style={{
          backgroundColor: "#ffffff",
          minHeight: "44px",
          borderTop: "1px solid rgba(0,0,0,0.08)",
        }}
      >
        {/* PROMPT_TITLE_PLACEHOLDER — editable on click */}
        <div
          id="PROMPT_TITLE_PLACEHOLDER"
          data-ui-id="prompt-title"
          data-ui-type="content-area"
          data-ui-description="Active prompt title — click to edit"
          className="flex-1 min-w-0"
        >
          {isEditingTitle ? (
            <input
              ref={titleInputRef}
              type="text"
              value={editedTitle}
              onChange={(e) => setEditedTitle(e.target.value)}
              onKeyDown={handleTitleKeyDown}
              onBlur={handleTitleSave}
              placeholder="Enter prompt title..."
              className="w-full text-sm font-semibold text-gray-900 bg-white border-2 border-[#4e68d2] rounded px-2 py-1 outline-none"
              style={{ boxShadow: "0 0 0 2px rgba(78, 104, 210, 0.15)" }}
            />
          ) : (
            <button
              onClick={() => setIsEditingTitle(true)}
              className="w-full text-left text-sm font-semibold text-gray-900 truncate bg-transparent border border-transparent hover:border-gray-300 rounded px-2 py-1 cursor-pointer transition-colors"
              title="Click to edit title"
            >
              {promptTitle || (
                <span className="text-gray-500 italic">
                  prompt_title: Placeholder title text goes here...
                </span>
              )}
            </button>
          )}
        </div>

        {/* RIGHT CONTROLS — version, tags, ID, author, score, COLUMN FLIP */}
        <div
          data-ui-id="prompt-controls"
          data-ui-type="layout"
          data-ui-description="Prompt metadata badges + layout controls"
          className="flex items-center gap-3 flex-shrink-0"
        >
          {/* VERSION */}
          <div
            className="relative"
            
            
            
            
          >
            <VersionManager sessionId={promptId} currentVersion={currentVersion} />
          </div>

          {/* TAGS */}
          <div
            id="TAGS_PLACEHOLDER"
            data-ui-id="prompt-tags"
            data-ui-type="button"
            data-ui-description="Prompt tags — click to add/edit tags"
            className="flex items-center gap-1 text-xs text-amber-600 font-medium cursor-pointer"
          >
            <svg viewBox="0 0 16 16" fill="none" className="w-3.5 h-3.5">
              <path d="M8 3L14 13H2L8 3Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" />
              <path d="M8 7v3M8 11.5v.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
            </svg>
            {tags ?? "No tags +"}
          </div>

          {/* ID */}
          <div
            id="ID_PLACEHOLDER"
            data-ui-id="prompt-id"
            data-ui-type="content-area"
            data-ui-description="Unique prompt identifier"
            className="text-xs text-gray-600 font-medium"
          >
            ID: {promptId ?? "PR-0000"}
          </div>

          {/* AUTHOR */}
          <div
            id="AUTHOR_PLACEHOLDER"
            data-ui-id="prompt-author"
            data-ui-type="button"
            data-ui-description="Prompt author — click to change"
            className="text-xs text-gray-600 cursor-pointer"
          >
            Author: {author ?? "—"}
          </div>

          {/* SCORE */}
          <button
            id="SCORE_PLACEHOLDER"
            data-ui-id="prompt-score"
            data-ui-type="button"
            data-ui-description="Computed prompt score — click to expand"
            className="flex items-center gap-1 px-3 py-0.5 rounded border text-xs font-medium text-gray-700 border-gray-400 bg-white hover:bg-gray-50 transition-colors"
          >
            {score ?? "Score N/A"}
            <svg viewBox="0 0 12 12" fill="none" className="w-3 h-3 opacity-60">
              <path d="M3 4.5l3 3 3-3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </button>

          {/* COLUMN FLIP — layout control at far right of Row 2 */}
          {onToggleFlip && (
            <ColumnFlipToggle flipped={flipped ?? false} onToggle={onToggleFlip} />
          )}
        </div>
      </div>
      )}

    </div>
  );
}

// frontend/src/components/lit/left-column-header.ts
/**
 * <left-column-header> — the prompt's own bar: what this package is called, which
 * version of it is on screen, and what is known about it.
 *
 * WHY IT MOVED OFF REACT. Everything else about a prompt already lives in the surface —
 * the sections are data-bound paths the AI writes, and that is why a person can insert a
 * tool or a seat without anything bespoke. This bar was the last piece still owned by the
 * shell, so the TITLE in particular could only be changed through a callback the shell
 * handed down: no path, no tag, nothing the AI could reach. Moving it in makes the title
 * a value like every other value, so she can read it, ask about it, and set it.
 *
 * WHAT IS WIRED AND WHAT IS NOT. This is a straight carry of the React bar
 * (`components/LeftColumnHeader.tsx`, row 2) with its state made explicit, and some of it
 * has nothing behind it yet. Those are marked in place rather than drawn as though they
 * work — a control that takes a click and does nothing is indistinguishable from a broken
 * one, which is the failure this codebase keeps writing down.
 *
 *   title    WIRED   editable here, and settable by the AI (see the `title` prop and the
 *                    `a2ui:set-title` path in the host)
 *   version  WIRED   the label only. The list and restore are the React VersionManager's
 *                    job today and are marked as not yet moved.
 *   ID       WIRED   display only. Kept because the owner reads it while testing; not
 *                    something a customer needs to see.
 *   tags     PLACEHOLDER  drawn, inert, says so
 *   author   PLACEHOLDER  drawn, inert, says so
 *   score    PLACEHOLDER  drawn, inert, says so
 *   flip     INACTIVE     the owner: "you don't have to do the flip function. You can
 *                         just keep that inactive at the moment"
 *
 * DESIGN. Colours, sizes and spacing are the React bar's, which its own docstring says
 * were taken from the design. nothing here is invented.
 */
import { LitElement, html, css, nothing } from 'lit';
import { designTokens } from '@/shared/design-tokens';

/** One inert control. Drawn, labelled, and honest about taking no click. */
function placeholder(label: string, value: unknown, cls: string) {
  return html`
    <span class=${cls} data-inert="true" title=${`${label} — not wired up yet`}
          aria-disabled="true">${value}</span>`;
}

export class LeftColumnHeader extends LitElement {
  static properties = {
    /** The package's title. Empty draws the prompt to name it. */
    title: { type: String },
    /** The version on screen, as a number. 0 or absent draws the empty label. */
    version: { type: Number },
    /** The package's id. Display only — the owner reads it while testing. */
    promptId: { type: String, attribute: 'prompt-id' },
    /** True while the title field is open. Local, but declared so the host can see it. */
    editing: { type: Boolean, reflect: true },
  };

  declare title: string;
  declare version: number;
  declare promptId: string;
  declare editing: boolean;

  /** What the person is typing, before it is committed. */
  private _draft = '';

  static styles = [
    designTokens,
    css`
      :host {
        display: block;
        flex: 0 0 auto;
        background: #ffffff;
        border-top: 1px solid rgba(0, 0, 0, 0.08);
        min-height: 44px;
        /*
         * THE DROP SHADOW IS THE DRAWING'S, not a decoration added here. It was on the
         * React wrapper (#left-column-header, boxShadow 0 8px 24px rgba(0,0,0,0.25))
         * and it is what lifts the bar off the prompt below it — the bar and the sections
         * are both white, so without it they read as one surface with a seam.
         */
        box-shadow: 0 8px 24px rgba(0, 0, 0, 0.25);
        position: relative;
        z-index: 1;
      }
      .bar {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 16px;
        padding: 0 16px;
        min-height: 44px;
      }

      /* ── the title, which is the one field a person edits here ───────────── */
      .title-slot { flex: 1 1 0%; min-width: 0; }
      .title-btn {
        width: 100%;
        text-align: left;
        font: inherit;
        font-size: 14px;
        font-weight: 600;
        color: #111827;
        background: transparent;
        border: 1px solid transparent;
        border-radius: 4px;
        padding: 4px 8px;
        cursor: pointer;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      }
      .title-btn:hover { border-color: #d1d5db; }
      .title-empty { color: #6b7280; font-style: italic; font-weight: 500; }
      .title-input {
        width: 100%;
        box-sizing: border-box;
        font: inherit;
        font-size: 14px;
        font-weight: 600;
        color: #111827;
        background: #ffffff;
        border: 2px solid #4e68d2;
        border-radius: 4px;
        padding: 4px 8px;
        outline: none;
        box-shadow: 0 0 0 2px rgba(78, 104, 210, 0.15);
      }

      /* ── the controls on the right ───────────────────────────────────────── */
      .controls {
        display: flex;
        align-items: center;
        gap: 12px;
        flex-shrink: 0;
      }
      .meta {
        font-size: 12px;
        font-weight: 500;
        color: #4b5563;
        white-space: nowrap;
      }
      /* No muted state to style for an absent id: it draws NO line. A draft is a normal
         thing to have, not a field waiting to be filled. */
      .version { font-size: 12px; font-weight: 600; color: #4b5563; white-space: nowrap; }
      .version-empty { color: #9ca3af; font-weight: 500; }
      .tag {
        display: flex;
        align-items: center;
        gap: 4px;
        font-size: 12px;
        font-weight: 500;
        color: #d97706; /* text-amber-600 in the React bar */
      }
      .tag svg { width: 14px; height: 14px; }
      /*
       * AN INERT CONTROL LOOKS INERT. The three that have nothing behind them carry a
       * dashed underline rather than a hover state — a hover that promises a click and
       * a click that does nothing is how a person concludes the app is broken.
       */
      .inert {
        border-bottom: 1px dashed rgba(0, 0, 0, 0.28);
        cursor: default;
      }
      .score {
        display: flex;
        align-items: center;
        gap: 4px;
        padding: 2px 12px;
        border-radius: 4px;
        border: 1px solid #9ca3af;
        background: #ffffff;
        font-size: 12px;
        font-weight: 500;
        color: #374151;
      }
      .score svg { width: 12px; height: 12px; opacity: 0.6; }
      .flip {
        font-size: 12px;
        font-weight: 600;
        color: #9ca3af;
        padding: 2px 8px;
        border-radius: 4px;
        border: 1px dashed rgba(0, 0, 0, 0.28);
      }
    `,
  ];

  constructor() {
    super();
    this.title = '';
    this.version = 0;
    this.promptId = '';
    this.editing = false;
  }

  /** Enter commits, Escape abandons — the React bar's own keys, kept. */
  private _onKey = (e: KeyboardEvent): void => {
    if (e.key === 'Enter') { e.preventDefault(); this._commit(); }
    else if (e.key === 'Escape') { e.preventDefault(); this._cancel(); }
  };

  private _commit(): void {
    this.editing = false;
    const next = this._draft.trim();
    // A title is not cleared by blurring an empty field: an empty submit is a cancel,
    // which is what the React version did by testing `trimmed &&` before dispatching.
    if (!next || next === this.title) return;
    this.title = next;
    this.dispatchEvent(new CustomEvent('title-change', {
      bubbles: true, composed: true, detail: { title: next },
    }));
  }

  private _cancel(): void {
    this.editing = false;
    this._draft = this.title;
  }

  private _beginEdit(): void {
    this._draft = this.title;
    this.editing = true;
  }

  protected updated(changed: Map<string, unknown>): void {
    // The field owns the caret, so it is focused after the render that created it.
    if (changed.has('editing') && this.editing) {
      const input = this.renderRoot.querySelector('input') as HTMLInputElement | null;
      input?.focus();
      input?.select();
    }
  }

  render() {
    const title = this.title || '';
    return html`
      <div class="bar">
        <div class="title-slot">
          ${this.editing
            ? html`<input class="title-input" type="text" .value=${this._draft}
                          placeholder="Enter prompt title..."
                          @input=${(e: Event) => { this._draft = (e.target as HTMLInputElement).value; }}
                          @keydown=${this._onKey}
                          @blur=${() => this._commit()}>`
            : html`<button class="title-btn" type="button" title="Click to edit title"
                           @click=${() => this._beginEdit()}>
                     ${title || html`<span class="title-empty">Untitled prompt — give it a name</span>`}
                   </button>`}
        </div>

        <div class="controls">
          <span class="version ${this.version ? '' : 'version-empty'}">
            ${this.version ? `Editing Version v${this.version}` : 'Editing Version —'}
          </span>

          ${placeholder('Tags', html`<svg viewBox="0 0 16 16" fill="none"><path d="M8 3L14 13H2L8 3Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/><path d="M8 7v3M8 11.5v.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>No tags +`, 'tag inert')}

          ${/*
             * NO ID DRAWS NOTHING AT ALL. There is no such thing as a package that is
             * "missing" an id: it is a draft, and a draft is a normal thing to have —
             * people try something out and choose not to keep it, which is their call and
             * not a state worth flagging. The owner, 2026-09-28: "unsaved package needs
             * nothing... a lot of unsaved packages. It's actually a user choice."
             *
             * When there IS an id it is TRUNCATED TO FIVE CHARACTERS, with the whole one on
             * hover. A UUID is 36 characters that pushed the title out of the way, which is
             * the opposite of what a header is for; five is enough to tell two packages
             * apart at a glance and the full value is one hover away for the testing it
             * exists for.
             */ ''}
          ${this.promptId
            ? html`<span class="meta" title="Full id: ${this.promptId}"
                  >ID: ${this.promptId.slice(0, 5)}…</span>`
            : nothing}

          ${placeholder('Author', 'Author: —', 'meta inert')}

          ${placeholder('Score', html`Score N/A<svg viewBox="0 0 12 12" fill="none"><path d="M3 4.5l3 3 3-3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`, 'score inert')}

          <span class="flip" title="Column flip — not wired up yet">Flip</span>
        </div>
      </div>
    `;
  }
}

if (!customElements.get('left-column-header')) {
  customElements.define('left-column-header', LeftColumnHeader);
}

declare global {
  interface HTMLElementTagNameMap {
    'left-column-header': LeftColumnHeader;
  }
}
